<a href="https://colab.research.google.com/github/Narae-210/Python-self-study/blob/main/Numpyselfstudy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

x = np.arange(1,13,1).reshape(3,4)

print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
print(x[[0,2],[1]])

[ 2 10]
